/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/products/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Products Endpoint */
        get: operations["search_products_endpoint_api_products_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product History Endpoint
         * @description 特定商品の価格履歴を取得する。
         *
         *     ID (UUID) または JANコードで商品を特定し、過去指定日数の価格推移を
         *     日付・サイトごとにグルーピングして返却する。
         */
        get: operations["get_product_history_endpoint_api_products__id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cards */
        get: operations["list_cards_api_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card */
        get: operations["get_card_api_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description 認証ユーザー自身のプロファイルを返す。
         *
         *     未保存時は 200 + デフォルト値 + `updatedAt: null` を返し、DB へのレコード
         *     作成は行わない（docs/design/user-profile.md §3.1）。
         */
        get: operations["get_profile_api_me_profile_get"];
        /**
         * Update Profile
         * @description 全フィールド必須の PUT で UserProfile を全置換する（初回 INSERT を含む）。
         *
         *     `default_card_id` が指定されカードが存在しない場合は 422（FK
         *     IntegrityError 経由ではなく事前 SELECT でドメインエラーに翻訳）。
         */
        put: operations["update_profile_api_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usage
         * @description 認証ユーザー自身の当月利用実績を全サイト分返す。
         *
         *     未保存のサイトは 200 + 0 デフォルトを返す（404 ではない）。
         *     profile GET と同パターン（docs/plans/phase3-analytics-suggestion.md §3.2）。
         */
        get: operations["get_usage_api_me_usage_get"];
        /**
         * Update Usage
         * @description 指定サイト×月の利用実績を全置換 UPSERT する。
         *
         *     同一 (site, month) への再 PUT は値を上書きする（INSERT されない）。
         */
        put: operations["update_usage_api_me_usage_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/update-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger Update Prices */
        get: operations["trigger_update_prices_api_cron_update_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BreakdownEntry
         * @description PricingEngine の内訳 1 件。camelCase 変換不要（すべて lowercase）。
         *
         *     Why RewardEntry をそのまま使わないか:
         *         engine.py の RewardEntry は dataclass であり ORM に非依存の純粋関数層。
         *         HTTP レスポンス向けシリアライズの責務はスキーマ層に持たせるため、
         *         Pydantic BaseModel として別定義する。
         */
        BreakdownEntry: {
            /** Label */
            label: string;
            /** Rate */
            rate: number;
            /** Points */
            points: number;
            /** Note */
            note: string;
        };
        /** CardResponse */
        CardResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Baserewardrate */
            baseRewardRate: number;
            /** Annualfee */
            annualFee: number;
            /** Specialrewards */
            specialRewards: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ListingOut
         * @description 検索結果 1 件に含まれる EC サイトリスト情報。
         *
         *     Why from_attributes=False（デフォルト）:
         *         router 側で EcSiteProduct ORM から明示的に構築するため、
         *         ORM 属性マッピングは不要。
         */
        ListingOut: {
            /** Sitetype */
            siteType: string;
            /** Siteproductid */
            siteProductId: string;
            /** Url */
            url: string;
            /** Points */
            points: number | null;
            /** Effectiveprice */
            effectivePrice: number | null;
            /** Breakdown */
            breakdown: components["schemas"]["BreakdownEntry"][] | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MonthlyUsageItemResponse
         * @description PUT /api/me/usage のレスポンス（1 件）。
         *
         *     Why month を含む:
         *         PUT は特定サイト×特定月を全置換するため、確認応答として month を返す。
         */
        MonthlyUsageItemResponse: {
            /** Site */
            site: string;
            /** Month */
            month: string;
            /** Amountspent */
            amountSpent: number;
            /** Pointsearned */
            pointsEarned: number;
            /** Shopcount */
            shopCount: number;
        };
        /**
         * MonthlyUsageResponse
         * @description GET /api/me/usage のレスポンス（当月全サイト）。
         */
        MonthlyUsageResponse: {
            /** Month */
            month: string;
            /** Items */
            items: components["schemas"]["MonthlyUsageSiteEntry"][];
        };
        /**
         * MonthlyUsageSiteEntry
         * @description GET /api/me/usage レスポンスの 1 サイト分エントリ。
         *
         *     Why from_attributes=False（デフォルト）:
         *         ルーター側で ORM MonthlyUsage から手動マッピングする（ListingOut と同パターン）。
         *         ORM enum の value（小文字）を site フィールドに明示的に渡す。
         */
        MonthlyUsageSiteEntry: {
            /** Site */
            site: string;
            /** Amountspent */
            amountSpent: number;
            /** Pointsearned */
            pointsEarned: number;
            /** Shopcount */
            shopCount: number;
        };
        /**
         * MonthlyUsageUpdate
         * @description PUT /api/me/usage のリクエストボディ。全フィールド必須・全置換 UPSERT。
         *
         *     Why extra="forbid":
         *         GET レスポンスの形（month + items のネスト）を PUT body に流用するバグを
         *         検出する（ADR-013 §2 / UserProfileUpdate と同パターン）。
         *     Why Literal["amazon", "rakuten", "yahoo"]:
         *         wire format は小文字 value 固定。大文字（"AMAZON"）や不正値は 422 で弾く。
         */
        MonthlyUsageUpdate: {
            /**
             * Site
             * @enum {string}
             */
            site: "amazon" | "rakuten" | "yahoo";
            /** Month */
            month: string;
            /** Amountspent */
            amountSpent: number;
            /** Pointsearned */
            pointsEarned: number;
            /** Shopcount */
            shopCount: number;
        };
        /**
         * PersonalizationMeta
         * @description パーソナライズ適用状態のメタ情報。
         */
        PersonalizationMeta: {
            /** Applied */
            applied: boolean;
            /** Rakutenrank */
            rakutenRank: string | null;
            /** Hascard */
            hasCard: boolean;
        };
        /**
         * PriceHistoryEntry
         * @description 特定日の全サイト価格推移。
         *
         *     Why dictionary format:
         *         charts (recharts) expect an array of objects where each key is a line
         *         to be plotted.
         */
        PriceHistoryEntry: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Sites */
            sites: {
                [key: string]: components["schemas"]["SiteHistory"];
            };
        };
        /**
         * ProductHistoryResponse
         * @description 価格履歴APIのトップレベルレスポンス。
         */
        ProductHistoryResponse: {
            /**
             * Productid
             * Format: uuid
             */
            productId: string;
            /** Histories */
            histories: components["schemas"]["PriceHistoryEntry"][];
        };
        /** ProductSearchEnvelope */
        ProductSearchEnvelope: {
            /** Items */
            items: components["schemas"]["ProductSummary"][];
            /** Page */
            page: number;
            /** Totalpages */
            totalPages: number;
            /** Totalcount */
            totalCount: number;
            meta: components["schemas"]["SearchMeta"];
        };
        /** ProductSummary */
        ProductSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Imageurl */
            imageUrl: string | null;
            /** Tags */
            tags: string[];
            /** Instock */
            inStock: boolean;
            /** Currentprice */
            currentPrice: number | null;
            /** Listings */
            listings?: components["schemas"]["ListingOut"][];
        };
        /**
         * RakutenRank
         * @enum {string}
         */
        RakutenRank: "regular" | "silver" | "gold" | "platinum" | "diamond";
        /**
         * SearchMeta
         * @description 検索レスポンスのメタフィールド。認証有無に関わらず常に返す。
         */
        SearchMeta: {
            personalization: components["schemas"]["PersonalizationMeta"];
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * SiteHistory
         * @description 特定サイト・時点の価格情報。
         *
         *     Why SiteHistory (not PricePoint): docs/plans/phase2-price-history.md T-10
         *     で定義された正式名称。OpenAPI スキーマ名として公開される。
         */
        SiteHistory: {
            /** Price */
            price: number;
            /** Points */
            points: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Accesstoken */
            accessToken: string;
            /**
             * Tokentype
             * @default bearer
             */
            tokenType: string;
        };
        /** UserProfileResponse */
        UserProfileResponse: {
            rakutenRank: components["schemas"]["RakutenRank"];
            /** Isamazonprime */
            isAmazonPrime: boolean;
            /** Yahoopremium */
            yahooPremium: boolean;
            /** Israkutenmobile */
            isRakutenMobile: boolean;
            /** Ispaypaylinked */
            isPayPayLinked: boolean;
            /** Defaultcardid */
            defaultCardId: number | null;
            defaultCard: components["schemas"]["CardResponse"] | null;
            /** Updatedat */
            updatedAt: string | null;
        };
        /** UserProfileUpdate */
        UserProfileUpdate: {
            rakutenRank: components["schemas"]["RakutenRank"];
            /** Isamazonprime */
            isAmazonPrime: boolean;
            /** Yahoopremium */
            yahooPremium: boolean;
            /** Israkutenmobile */
            isRakutenMobile: boolean;
            /** Ispaypaylinked */
            isPayPayLinked: boolean;
            /** Defaultcardid */
            defaultCardId: number | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_products_endpoint_api_products_search_get: {
        parameters: {
            query: {
                q: string;
                inStock?: boolean | null;
                priceMin?: number | null;
                priceMax?: number | null;
                sort?: "relevance" | "price_asc" | "price_desc" | "newest";
                page?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSearchEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_history_endpoint_api_products__id__history_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cards_api_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"][];
                };
            };
        };
    };
    get_card_api_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_me_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_me_profile_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description default_card_id does not reference an existing card */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_usage_api_me_usage_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyUsageResponse"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_usage_api_me_usage_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthlyUsageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyUsageItemResponse"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_update_prices_api_cron_update_prices_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
