/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/products/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Products Endpoint */
        get: operations["search_products_endpoint_api_products_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cards */
        get: operations["list_cards_api_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card */
        get: operations["get_card_api_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description 認証ユーザー自身のプロファイルを返す。
         *
         *     未保存時は 200 + デフォルト値 + `updatedAt: null` を返し、DB へのレコード
         *     作成は行わない（docs/design/user-profile.md §3.1）。
         */
        get: operations["get_profile_api_me_profile_get"];
        /**
         * Update Profile
         * @description 全フィールド必須の PUT で UserProfile を全置換する（初回 INSERT を含む）。
         *
         *     `default_card_id` が指定されカードが存在しない場合は 422（FK
         *     IntegrityError 経由ではなく事前 SELECT でドメインエラーに翻訳）。
         */
        put: operations["update_profile_api_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/update-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger Update Prices */
        get: operations["trigger_update_prices_api_cron_update_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BreakdownEntry
         * @description PricingEngine の内訳 1 件。camelCase 変換不要（すべて lowercase）。
         *
         *     Why RewardEntry をそのまま使わないか:
         *         engine.py の RewardEntry は dataclass であり ORM に非依存の純粋関数層。
         *         HTTP レスポンス向けシリアライズの責務はスキーマ層に持たせるため、
         *         Pydantic BaseModel として別定義する。
         */
        BreakdownEntry: {
            /** Label */
            label: string;
            /** Rate */
            rate: number;
            /** Points */
            points: number;
            /** Note */
            note: string;
        };
        /** CardResponse */
        CardResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Baserewardrate */
            baseRewardRate: number;
            /** Annualfee */
            annualFee: number;
            /** Specialrewards */
            specialRewards: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ListingOut
         * @description 検索結果 1 件に含まれる EC サイトリスト情報。
         *
         *     Why from_attributes=False（デフォルト）:
         *         router 側で EcSiteProduct ORM から明示的に構築するため、
         *         ORM 属性マッピングは不要。
         */
        ListingOut: {
            /** Sitetype */
            siteType: string;
            /** Siteproductid */
            siteProductId: string;
            /** Url */
            url: string;
            /** Points */
            points: number | null;
            /** Effectiveprice */
            effectivePrice: number | null;
            /** Breakdown */
            breakdown: components["schemas"]["BreakdownEntry"][] | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * PersonalizationMeta
         * @description パーソナライズ適用状態のメタ情報。
         */
        PersonalizationMeta: {
            /** Applied */
            applied: boolean;
            /** Rakutenrank */
            rakutenRank: string | null;
            /** Hascard */
            hasCard: boolean;
        };
        /** ProductSearchEnvelope */
        ProductSearchEnvelope: {
            /** Items */
            items: components["schemas"]["ProductSummary"][];
            /** Page */
            page: number;
            /** Totalpages */
            totalPages: number;
            /** Totalcount */
            totalCount: number;
            meta: components["schemas"]["SearchMeta"];
        };
        /** ProductSummary */
        ProductSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Imageurl */
            imageUrl: string | null;
            /** Tags */
            tags: string[];
            /** Instock */
            inStock: boolean;
            /** Currentprice */
            currentPrice: number | null;
            /** Listings */
            listings?: components["schemas"]["ListingOut"][];
        };
        /**
         * RakutenRank
         * @enum {string}
         */
        RakutenRank: "regular" | "silver" | "gold" | "platinum" | "diamond";
        /**
         * SearchMeta
         * @description 検索レスポンスのメタフィールド。認証有無に関わらず常に返す。
         */
        SearchMeta: {
            personalization: components["schemas"]["PersonalizationMeta"];
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Accesstoken */
            accessToken: string;
            /**
             * Tokentype
             * @default bearer
             */
            tokenType: string;
        };
        /** UserProfileResponse */
        UserProfileResponse: {
            rakutenRank: components["schemas"]["RakutenRank"];
            /** Isamazonprime */
            isAmazonPrime: boolean;
            /** Yahoopremium */
            yahooPremium: boolean;
            /** Israkutenmobile */
            isRakutenMobile: boolean;
            /** Ispaypaylinked */
            isPayPayLinked: boolean;
            /** Defaultcardid */
            defaultCardId: number | null;
            defaultCard: components["schemas"]["CardResponse"] | null;
            /** Updatedat */
            updatedAt: string | null;
        };
        /** UserProfileUpdate */
        UserProfileUpdate: {
            rakutenRank: components["schemas"]["RakutenRank"];
            /** Isamazonprime */
            isAmazonPrime: boolean;
            /** Yahoopremium */
            yahooPremium: boolean;
            /** Israkutenmobile */
            isRakutenMobile: boolean;
            /** Ispaypaylinked */
            isPayPayLinked: boolean;
            /** Defaultcardid */
            defaultCardId: number | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_products_endpoint_api_products_search_get: {
        parameters: {
            query: {
                q: string;
                inStock?: boolean | null;
                priceMin?: number | null;
                priceMax?: number | null;
                sort?: "relevance" | "price_asc" | "price_desc" | "newest";
                page?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSearchEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cards_api_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"][];
                };
            };
        };
    };
    get_card_api_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_me_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_me_profile_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description default_card_id does not reference an existing card */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_update_prices_api_cron_update_prices_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
